/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bundle;

import bundle.download.DownloadManager;
import bundle.installer.BundleInstaller;

public class App {
    public static final BundleInstaller INSTALLER;

    public static void main(String[] args) {
        INSTALLER.openUI();
    }

    static {
        DownloadManager.setup();
        INSTALLER = new BundleInstaller();
    }
}
